baseURL = 'https://frontier.scetrov.live/'
languageCode = 'en-us'
title = 'Unofficial EVE Frontier Development Notes'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = "frontier-dark"